/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface PaperDraftParams {
  'title' : string,
  'subject' : string,
  'numQuestions' : bigint,
  'grade' : string,
  'marksPerQuestion' : bigint,
  'questionDistribution' : {
    'easy' : bigint,
    'hard' : bigint,
    'medium' : bigint,
  },
}
export interface PaperMetaData {
  'title' : string,
  'creator' : Principal,
  'subject' : string,
  'grade' : string,
}
export interface Question {
  'marks' : bigint,
  'difficulty' : Difficulty,
  'text' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export interface QuestionPaper {
  'id' : bigint,
  'totalMarks' : bigint,
  'metadata' : PaperMetaData,
  'questions' : Array<Question>,
}
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'teacher' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createPaperDraft' : ActorMethod<
    [PaperMetaData, PaperDraftParams, Array<Question>],
    QuestionPaper
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getPaper' : ActorMethod<[bigint], QuestionPaper>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllPapers' : ActorMethod<[], Array<QuestionPaper>>,
  'listPapersByCreator' : ActorMethod<[Principal], Array<QuestionPaper>>,
  'mergePapers' : ActorMethod<[PaperMetaData, Array<bigint>], QuestionPaper>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPapersByTitle' : ActorMethod<[string], Array<QuestionPaper>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];