/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaperMetaData = IDL.Record({
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'subject' : IDL.Text,
  'grade' : IDL.Text,
});
export const PaperDraftParams = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'numQuestions' : IDL.Nat,
  'grade' : IDL.Text,
  'marksPerQuestion' : IDL.Nat,
  'questionDistribution' : IDL.Record({
    'easy' : IDL.Nat,
    'hard' : IDL.Nat,
    'medium' : IDL.Nat,
  }),
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Question = IDL.Record({
  'marks' : IDL.Nat,
  'difficulty' : Difficulty,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const QuestionPaper = IDL.Record({
  'id' : IDL.Nat,
  'totalMarks' : IDL.Nat,
  'metadata' : PaperMetaData,
  'questions' : IDL.Vec(Question),
});
export const UserRole = IDL.Variant({
  'teacher' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createPaperDraft' : IDL.Func(
      [PaperMetaData, PaperDraftParams, IDL.Vec(Question)],
      [QuestionPaper],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getPaper' : IDL.Func([IDL.Nat], [QuestionPaper], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPapers' : IDL.Func([], [IDL.Vec(QuestionPaper)], ['query']),
  'listPapersByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QuestionPaper)],
      ['query'],
    ),
  'mergePapers' : IDL.Func(
      [PaperMetaData, IDL.Vec(IDL.Nat)],
      [QuestionPaper],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPapersByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuestionPaper)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaperMetaData = IDL.Record({
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'subject' : IDL.Text,
    'grade' : IDL.Text,
  });
  const PaperDraftParams = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'numQuestions' : IDL.Nat,
    'grade' : IDL.Text,
    'marksPerQuestion' : IDL.Nat,
    'questionDistribution' : IDL.Record({
      'easy' : IDL.Nat,
      'hard' : IDL.Nat,
      'medium' : IDL.Nat,
    }),
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Question = IDL.Record({
    'marks' : IDL.Nat,
    'difficulty' : Difficulty,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const QuestionPaper = IDL.Record({
    'id' : IDL.Nat,
    'totalMarks' : IDL.Nat,
    'metadata' : PaperMetaData,
    'questions' : IDL.Vec(Question),
  });
  const UserRole = IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createPaperDraft' : IDL.Func(
        [PaperMetaData, PaperDraftParams, IDL.Vec(Question)],
        [QuestionPaper],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getPaper' : IDL.Func([IDL.Nat], [QuestionPaper], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPapers' : IDL.Func([], [IDL.Vec(QuestionPaper)], ['query']),
    'listPapersByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QuestionPaper)],
        ['query'],
      ),
    'mergePapers' : IDL.Func(
        [PaperMetaData, IDL.Vec(IDL.Nat)],
        [QuestionPaper],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPapersByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuestionPaper)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };